using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TypeForge.Generator;

/// <summary>
/// Emits generated forging code for TypeForge forger classes.
/// </summary>
internal sealed class ForgeCodeEmitter
{
    private readonly Compilation _compilation;

    public ForgeCodeEmitter(Compilation compilation)
    {
        _compilation = compilation;
    }

    public string GenerateForger(ForgerInfo forger, SourceProductionContext context)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        var ns = forger.Symbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()}");
            sb.AppendLine("{");
        }

        // Class declaration with same accessibility
        var accessibility = GetAccessibilityKeyword(forger.Symbol.DeclaredAccessibility);
        sb.AppendLine($"    {accessibility} partial class {forger.Symbol.Name}");
        sb.AppendLine("    {");

        // Find and implement partial methods
        var partialMethods = forger.Symbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.IsPartialDefinition && !m.ReturnsVoid || (m.IsPartialDefinition && m.ReturnsVoid && HasForgeIntoPattern(m)));

        foreach (var method in partialMethods)
        {
            var generatedMethod = GenerateMethod(method, forger, context);
            if (!string.IsNullOrEmpty(generatedMethod))
            {
                sb.AppendLine(generatedMethod);
            }
        }

        sb.AppendLine("    }");

        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static bool HasForgeIntoPattern(IMethodSymbol method)
    {
        // Check if this is a ForgeInto pattern (void return with [UseExistingValue] parameter)
        return method.Parameters.Any(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute" ||
                a.AttributeClass?.ToDisplayString() == "TypeForge.UseExistingValueAttribute"));
    }

    private string GenerateMethod(IMethodSymbol method, ForgerInfo forger, SourceProductionContext context)
    {
        // Validate method has at least one parameter (source)
        if (method.Parameters.Length == 0)
        {
            return string.Empty;
        }

        var sourceType = method.Parameters[0].Type;
        var destinationType = method.ReturnType;

        // Handle ForgeInto pattern
        var useExistingParam = method.Parameters.FirstOrDefault(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute" ||
                a.AttributeClass?.ToDisplayString() == "TypeForge.UseExistingValueAttribute"));

        if (useExistingParam != null)
        {
            destinationType = useExistingParam.Type;
            return GenerateForgeIntoMethod(method, sourceType, destinationType as INamedTypeSymbol, forger, context);
        }

        if (destinationType is not INamedTypeSymbol destNamedType)
        {
            return string.Empty;
        }

        return GenerateForgeMethod(method, sourceType as INamedTypeSymbol, destNamedType, forger, context);
    }

    private string GenerateForgeMethod(
        IMethodSymbol method,
        INamedTypeSymbol? sourceType,
        INamedTypeSymbol destinationType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        if (sourceType == null)
            return string.Empty;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;

        // Method signature
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        sb.AppendLine($"        {accessibility} partial {destinationType.ToDisplayString()} {method.Name}({sourceType.ToDisplayString()} {sourceParam})");
        sb.AppendLine("        {");

        // Null check
        sb.AppendLine($"            if ({sourceParam} == null) return null!;");
        sb.AppendLine();

        // Get mappable properties
        var sourceProperties = GetMappableProperties(sourceType);
        var destProperties = GetMappableProperties(destinationType);

        // Build property mappings
        sb.AppendLine($"            return new {destinationType.ToDisplayString()}");
        sb.AppendLine("            {");

        foreach (var destProp in destProperties)
        {
            // Try to find matching source property by name
            var sourceProp = sourceProperties.FirstOrDefault(sp =>
                string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));

            if (sourceProp != null && CanAssign(sourceProp.Type, destProp.Type))
            {
                sb.AppendLine($"                {destProp.Name} = {sourceParam}.{sourceProp.Name},");
            }
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");

        return sb.ToString();
    }

    private string GenerateForgeIntoMethod(
        IMethodSymbol method,
        ITypeSymbol sourceType,
        INamedTypeSymbol? destinationType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        if (destinationType == null)
            return string.Empty;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;
        var destParam = method.Parameters.First(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute")).Name;

        // Method signature
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        sb.AppendLine($"        {accessibility} partial void {method.Name}({sourceType.ToDisplayString()} {sourceParam}, {destinationType.ToDisplayString()} {destParam})");
        sb.AppendLine("        {");

        // Null checks
        sb.AppendLine($"            if ({destParam} == null) throw new global::System.ArgumentNullException(nameof({destParam}));");
        sb.AppendLine($"            if ({sourceParam} == null) return;");
        sb.AppendLine();

        // Get mappable properties
        var sourceProperties = GetMappableProperties(sourceType as INamedTypeSymbol);
        var destProperties = GetMappableProperties(destinationType).Where(p => p.SetMethod != null);

        foreach (var destProp in destProperties)
        {
            var sourceProp = sourceProperties.FirstOrDefault(sp =>
                string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));

            if (sourceProp != null && CanAssign(sourceProp.Type, destProp.Type))
            {
                sb.AppendLine($"            {destParam}.{destProp.Name} = {sourceParam}.{sourceProp.Name};");
            }
        }

        sb.AppendLine("        }");

        return sb.ToString();
    }

    private static IEnumerable<IPropertySymbol> GetMappableProperties(INamedTypeSymbol? type)
    {
        if (type == null)
            return Enumerable.Empty<IPropertySymbol>();

        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                       !p.IsStatic &&
                       !p.IsIndexer &&
                       p.GetMethod != null);
    }

    private static bool CanAssign(ITypeSymbol source, ITypeSymbol dest)
    {
        // Simple type compatibility check
        if (SymbolEqualityComparer.Default.Equals(source, dest))
            return true;

        // Handle nullable to non-nullable (with potential runtime issue)
        if (source.NullableAnnotation == NullableAnnotation.Annotated &&
            dest.NullableAnnotation != NullableAnnotation.Annotated)
        {
            var underlyingSource = source.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            return SymbolEqualityComparer.Default.Equals(underlyingSource, dest);
        }

        // Handle inheritance
        var currentType = source;
        while (currentType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(currentType, dest))
                return true;
            currentType = currentType.BaseType;
        }

        // Handle interfaces
        foreach (var iface in source.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, dest))
                return true;
        }

        return false;
    }

    private static string GetAccessibilityKeyword(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private => "private",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
    }
}
