using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TypeForge.Generator;

/// <summary>
/// Emits generated forging code for TypeForge forger classes.
/// </summary>
internal sealed class ForgeCodeEmitter
{
    private readonly INamedTypeSymbol? _ignoreAttributeSymbol;
    private readonly INamedTypeSymbol? _forgePropertyAttributeSymbol;
    private readonly INamedTypeSymbol? _forgeFromAttributeSymbol;
    private readonly INamedTypeSymbol? _forgeWithAttributeSymbol;

    public ForgeCodeEmitter(Compilation compilation)
    {
        _ignoreAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.IgnoreAttribute");
        _forgePropertyAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.ForgePropertyAttribute");
        _forgeFromAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.ForgeFromAttribute");
        _forgeWithAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.ForgeWithAttribute");
    }

    public string GenerateForger(ForgerInfo forger, SourceProductionContext context)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        // Namespace
        var ns = forger.Symbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()}");
            sb.AppendLine("{");
        }

        // Class declaration with same accessibility
        var accessibility = GetAccessibilityKeyword(forger.Symbol.DeclaredAccessibility);
        sb.AppendLine($"    {accessibility} partial class {forger.Symbol.Name}");
        sb.AppendLine("    {");

        // Find and implement partial methods
        var partialMethods = forger.Symbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.IsPartialDefinition && !m.ReturnsVoid || (m.IsPartialDefinition && m.ReturnsVoid && HasForgeIntoPattern(m)));

        foreach (var method in partialMethods)
        {
            var generatedMethod = GenerateMethod(method, forger, context);
            if (!string.IsNullOrEmpty(generatedMethod))
            {
                sb.AppendLine(generatedMethod);
            }
        }

        sb.AppendLine("    }");

        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static bool HasForgeIntoPattern(IMethodSymbol method)
    {
        // Check if this is a ForgeInto pattern (void return with [UseExistingValue] parameter)
        return method.Parameters.Any(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute" ||
                a.AttributeClass?.ToDisplayString() == "TypeForge.UseExistingValueAttribute"));
    }

    private string GenerateMethod(IMethodSymbol method, ForgerInfo forger, SourceProductionContext context)
    {
        // Validate method has at least one parameter (source)
        if (method.Parameters.Length == 0)
        {
            return string.Empty;
        }

        var sourceType = method.Parameters[0].Type;
        var destinationType = method.ReturnType;

        // Handle ForgeInto pattern
        var useExistingParam = method.Parameters.FirstOrDefault(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute" ||
                a.AttributeClass?.ToDisplayString() == "TypeForge.UseExistingValueAttribute"));

        if (useExistingParam != null)
        {
            destinationType = useExistingParam.Type;
            return GenerateForgeIntoMethod(method, sourceType, destinationType as INamedTypeSymbol, forger, context);
        }

        // Check for collection mapping (List<T>, T[], IEnumerable<T>, etc.)
        var sourceElementType = GetCollectionElementType(sourceType);
        var destElementType = GetCollectionElementType(destinationType);
        if (sourceElementType != null && destElementType != null)
        {
            return GenerateCollectionForgeMethod(method, sourceType, destinationType, sourceElementType, destElementType, forger, context);
        }

        if (destinationType is not INamedTypeSymbol destNamedType)
        {
            return string.Empty;
        }

        return GenerateForgeMethod(method, sourceType as INamedTypeSymbol, destNamedType, forger, context);
    }

    private string GenerateForgeMethod(
        IMethodSymbol method,
        INamedTypeSymbol? sourceType,
        INamedTypeSymbol destinationType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        if (sourceType == null)
            return string.Empty;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;

        // Get ignored properties from [Ignore] attributes
        var ignoredProperties = GetIgnoredProperties(method);

        // Get property mappings from [ForgeProperty] attributes
        var propertyMappings = GetPropertyMappings(method);

        // Get resolver mappings from [ForgeFrom] attributes
        var resolverMappings = GetResolverMappings(method);

        // Get [ForgeWith] mappings for nested object forging
        var forgeWithMappings = GetForgeWithMappings(method);

        // Method signature
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        sb.AppendLine($"        {accessibility} partial {destinationType.ToDisplayString()} {method.Name}({sourceType.ToDisplayString()} {sourceParam})");
        sb.AppendLine("        {");

        // Null check
        sb.AppendLine($"            if ({sourceParam} == null) return null!;");
        sb.AppendLine();

        // Get mappable properties
        var sourceProperties = GetMappableProperties(sourceType);
        var destProperties = GetMappableProperties(destinationType);

        // Build property mappings
        sb.AppendLine($"            return new {destinationType.ToDisplayString()}");
        sb.AppendLine("            {");

        foreach (var destProp in destProperties)
        {
            // Skip ignored properties
            if (ignoredProperties.Contains(destProp.Name))
                continue;

            // Check if this property has a resolver from [ForgeFrom]
            if (resolverMappings.TryGetValue(destProp.Name, out var resolverMethodName))
            {
                // Find the source property path for this destination (if mapped via [ForgeProperty])
                string? sourcePropPath = null;
                ITypeSymbol? sourcePathLeafType = null;

                if (propertyMappings.TryGetValue(destProp.Name, out sourcePropPath))
                {
                    // Resolve the leaf type for the full path (handles nested paths like "Customer.Name")
                    sourcePathLeafType = ResolvePathLeafType(sourcePropPath, sourceType);
                }
                else
                {
                    // Try to find by same name
                    var matchingSourceProp = sourceProperties.FirstOrDefault(sp => sp.Name == destProp.Name);
                    if (matchingSourceProp != null)
                    {
                        sourcePropPath = matchingSourceProp.Name;
                        sourcePathLeafType = matchingSourceProp.Type;
                    }
                }

                // Find the resolver method - pass leaf type directly for proper overload selection
                var resolverMethod = FindResolverMethod(forger.Symbol, resolverMethodName, sourceType, sourcePathLeafType);

                if (resolverMethod == null)
                {
                    // Report diagnostic TF0008: Resolver method not found
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.ResolverMethodNotFound,
                        method.Locations.FirstOrDefault(),
                        resolverMethodName));
                    continue;
                }

                // Determine what to pass to the resolver
                var resolverParamType = resolverMethod.Parameters[0].Type;
                string resolverCall;

                if (SymbolEqualityComparer.Default.Equals(resolverParamType, sourceType) ||
                    CanAssign(sourceType, resolverParamType))
                {
                    // Pass the full source object
                    resolverCall = $"{resolverMethodName}({sourceParam})";
                }
                else if (sourcePropPath != null && sourcePathLeafType != null &&
                         CanAssign(sourcePathLeafType, resolverParamType))
                {
                    // Pass the source property value - use null-info to handle nullable expressions
                    var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropPath, sourceType);

                    // Handle Nullable<T> to T conversion with explicit cast
                    // Also handle lifted value types from null-conditional (e.g., source.Customer?.Age becomes int?)
                    var isLiftedValueType = hasNullConditional && sourcePathLeafType.IsValueType && GetNullableUnderlyingType(sourcePathLeafType) == null;
                    if (IsNullableToNonNullableValueType(sourcePathLeafType, resolverParamType) || isLiftedValueType)
                    {
                        resolverCall = $"{resolverMethodName}(({resolverParamType.ToDisplayString()}){sourceExpr}!)";
                    }
                    else
                    {
                        // Add null-forgiving if expression is nullable (from null-conditional or nullable ref type)
                        // but resolver param is non-nullable
                        var isNullableExpr = hasNullConditional || sourcePathLeafType.NullableAnnotation == NullableAnnotation.Annotated;
                        var nullForgiving = isNullableExpr && resolverParamType.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                        resolverCall = $"{resolverMethodName}({sourceExpr}{nullForgiving})";
                    }
                }
                else
                {
                    // Report diagnostic TF0009: Invalid resolver signature
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidResolverSignature,
                        method.Locations.FirstOrDefault(),
                        resolverMethodName));
                    continue;
                }

                sb.AppendLine($"                {destProp.Name} = {resolverCall},");
                continue;
            }

            // Check if this property has a [ForgeWith] mapping for nested object forging
            if (forgeWithMappings.TryGetValue(destProp.Name, out var forgingMethodName))
            {
                // Find matching source property by name or [ForgeProperty] mapping
                string? forgeWithSourcePropName = null;
                if (propertyMappings.TryGetValue(destProp.Name, out var mappedSource))
                {
                    forgeWithSourcePropName = mappedSource;
                }
                else
                {
                    var matchingSourceProp = sourceProperties.FirstOrDefault(sp =>
                        string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));
                    if (matchingSourceProp != null)
                        forgeWithSourcePropName = matchingSourceProp.Name;
                }

                if (forgeWithSourcePropName != null)
                {
                    var sourcePropertyType = ResolvePathLeafType(forgeWithSourcePropName, sourceType);
                    if (sourcePropertyType != null)
                    {
                        // Find the forging method on the forger class
                        var nestedForgeMethod = FindForgingMethod(forger.Symbol, forgingMethodName, sourcePropertyType, destProp.Type);
                        if (nestedForgeMethod != null)
                        {
                            var (sourceExpr, _) = GenerateSourceExpressionWithNullInfo(sourceParam, forgeWithSourcePropName, sourceType);
                            // Null source property => null destination (no nested call)
                            if (sourcePropertyType.IsReferenceType)
                            {
                                var localVarName = $"__forgeWith_{destProp.Name}";
                                sb.AppendLine($"                {destProp.Name} = {sourceExpr} is {{ }} {localVarName} ? {forgingMethodName}({localVarName}) : null!,");
                            }
                            else
                            {
                                sb.AppendLine($"                {destProp.Name} = {forgingMethodName}({sourceExpr}),");
                            }
                            continue;
                        }
                    }
                }

                // Report TF0008: method not found
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.ResolverMethodNotFound,
                    method.Locations.FirstOrDefault(),
                    forgingMethodName));
                continue;
            }

            // Check if this property has a mapping from [ForgeProperty]
            if (propertyMappings.TryGetValue(destProp.Name, out var sourcePropName))
            {
                var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropName, sourceType);
                // Add null-forgiving operator if destination is non-nullable and we have null-conditional
                var nullForgiving = hasNullConditional && destProp.Type.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                sb.AppendLine($"                {destProp.Name} = {sourceExpr}{nullForgiving},");
                continue;
            }

            // Try to find matching source property by name (convention)
            var sourceProp = sourceProperties.FirstOrDefault(sp =>
                string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));

            if (sourceProp != null && CanAssign(sourceProp.Type, destProp.Type))
            {
                // Handle Nullable<T> to T conversion using explicit cast which throws if null
                if (IsNullableToNonNullableValueType(sourceProp.Type, destProp.Type))
                {
                    sb.AppendLine($"                {destProp.Name} = ({destProp.Type.ToDisplayString()}){sourceParam}.{sourceProp.Name}!,");
                }
                else
                {
                    sb.AppendLine($"                {destProp.Name} = {sourceParam}.{sourceProp.Name},");
                }
            }
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");

        return sb.ToString();
    }

    private HashSet<string> GetIgnoredProperties(IMethodSymbol method)
    {
        var ignored = new HashSet<string>(StringComparer.Ordinal);

        if (_ignoreAttributeSymbol == null)
            return ignored;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _ignoreAttributeSymbol))
                continue;

            // The [Ignore] attribute takes params string[] propertyNames
            if (attr.ConstructorArguments.Length > 0)
            {
                var arg = attr.ConstructorArguments[0];
                if (arg.Kind == TypedConstantKind.Array)
                {
                    foreach (var item in arg.Values)
                    {
                        if (item.Value is string propName)
                        {
                            ignored.Add(propName);
                        }
                    }
                }
            }
        }

        return ignored;
    }

    /// <summary>
    /// Gets property mappings from [ForgeProperty] attributes.
    /// Returns a dictionary mapping destination property name to source property path.
    /// </summary>
    private Dictionary<string, string> GetPropertyMappings(IMethodSymbol method)
    {
        var mappings = new Dictionary<string, string>(StringComparer.Ordinal);

        if (_forgePropertyAttributeSymbol == null)
            return mappings;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _forgePropertyAttributeSymbol))
                continue;

            // [ForgeProperty(sourceProperty, destinationProperty)]
            if (attr.ConstructorArguments.Length >= 2)
            {
                var sourceProperty = attr.ConstructorArguments[0].Value as string;
                var destinationProperty = attr.ConstructorArguments[1].Value as string;

                if (!string.IsNullOrEmpty(sourceProperty) && !string.IsNullOrEmpty(destinationProperty))
                {
                    mappings[destinationProperty!] = sourceProperty!;
                }
            }
        }

        return mappings;
    }

    /// <summary>
    /// Gets resolver mappings from [ForgeFrom] attributes.
    /// Returns a dictionary mapping destination property name to resolver method name.
    /// </summary>
    private Dictionary<string, string> GetResolverMappings(IMethodSymbol method)
    {
        var resolvers = new Dictionary<string, string>(StringComparer.Ordinal);

        if (_forgeFromAttributeSymbol == null)
            return resolvers;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _forgeFromAttributeSymbol))
                continue;

            // [ForgeFrom(destinationProperty, resolverMethodName)]
            if (attr.ConstructorArguments.Length >= 2)
            {
                var destinationProperty = attr.ConstructorArguments[0].Value as string;
                var resolverMethodName = attr.ConstructorArguments[1].Value as string;

                if (!string.IsNullOrEmpty(destinationProperty) && !string.IsNullOrEmpty(resolverMethodName))
                {
                    resolvers[destinationProperty!] = resolverMethodName!;
                }
            }
        }

        return resolvers;
    }

    /// <summary>
    /// Gets [ForgeWith] mappings.
    /// Returns a dictionary mapping destination property name to forging method name.
    /// </summary>
    private Dictionary<string, string> GetForgeWithMappings(IMethodSymbol method)
    {
        var mappings = new Dictionary<string, string>(StringComparer.Ordinal);

        if (_forgeWithAttributeSymbol == null)
            return mappings;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _forgeWithAttributeSymbol))
                continue;

            // [ForgeWith(destinationProperty, forgingMethodName)]
            if (attr.ConstructorArguments.Length >= 2)
            {
                var destinationProperty = attr.ConstructorArguments[0].Value as string;
                var forgingMethodName = attr.ConstructorArguments[1].Value as string;

                if (!string.IsNullOrEmpty(destinationProperty) && !string.IsNullOrEmpty(forgingMethodName))
                {
                    mappings[destinationProperty!] = forgingMethodName!;
                }
            }
        }

        return mappings;
    }

    /// <summary>
    /// Finds a forging method on the forger class that accepts the given source type and returns the given destination type.
    /// </summary>
    private static IMethodSymbol? FindForgingMethod(INamedTypeSymbol forgerType, string methodName, ITypeSymbol sourcePropertyType, ITypeSymbol destPropertyType)
    {
        return forgerType.GetMembers(methodName)
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsPartialDefinition &&
                m.Parameters.Length == 1 &&
                !m.ReturnsVoid &&
                SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, sourcePropertyType) &&
                SymbolEqualityComparer.Default.Equals(m.ReturnType, destPropertyType));
    }

    /// <summary>
    /// Finds a resolver method in the forger class.
    /// Prefers exact type matches over assignable matches for deterministic overload selection.
    /// </summary>
    private IMethodSymbol? FindResolverMethod(INamedTypeSymbol forgerType, string methodName, ITypeSymbol sourceType, ITypeSymbol? preferredParamType)
    {
        var candidates = forgerType.GetMembers(methodName)
            .OfType<IMethodSymbol>()
            .Where(m => !m.ReturnsVoid && m.Parameters.Length == 1)
            .ToList();

        if (candidates.Count == 0)
            return null;

        // Prefer Method(TPreferredType) if preferredParamType is provided
        if (preferredParamType != null)
        {
            // First try exact match
            var exactMatch = candidates.FirstOrDefault(m =>
                SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, preferredParamType));
            if (exactMatch != null)
                return exactMatch;

            // Then try assignable match
            var assignableMatch = candidates.FirstOrDefault(m =>
                CanAssign(preferredParamType, m.Parameters[0].Type));
            if (assignableMatch != null)
                return assignableMatch;
        }

        // Fall back to Method(TSource) - prefer exact match first
        var exactSourceMatch = candidates.FirstOrDefault(m =>
            SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, sourceType));
        if (exactSourceMatch != null)
            return exactSourceMatch;

        var assignableSourceMatch = candidates.FirstOrDefault(m =>
            CanAssign(sourceType, m.Parameters[0].Type));

        return assignableSourceMatch ?? candidates.FirstOrDefault();
    }

    /// <summary>
    /// Generates the source expression for a property, handling nested paths.
    /// Returns a tuple of (expression, hasNullConditional).
    /// </summary>
    private (string Expression, bool HasNullConditional) GenerateSourceExpressionWithNullInfo(string sourceParam, string sourcePath, INamedTypeSymbol sourceType)
    {
        if (!sourcePath.Contains("."))
        {
            return ($"{sourceParam}.{sourcePath}", false);
        }

        // Handle nested path (e.g., "Customer.Name")
        var parts = sourcePath.Split('.');
        var expression = new StringBuilder(sourceParam);
        var currentType = sourceType;
        var hasNullConditional = false;

        for (int i = 0; i < parts.Length; i++)
        {
            var part = parts[i];
            var prop = GetMappableProperties(currentType).FirstOrDefault(p => p.Name == part);

            if (prop == null)
            {
                // Property not found, just append directly
                expression.Append($".{part}");
                continue;
            }

            // Add null-conditional for reference types (except the last property)
            if (i < parts.Length - 1 && prop.Type.IsReferenceType)
            {
                expression.Append($".{part}?");
                hasNullConditional = true;
            }
            else
            {
                expression.Append($".{part}");
            }

            if (prop.Type is INamedTypeSymbol namedType)
            {
                currentType = namedType;
            }
        }

        return (expression.ToString(), hasNullConditional);
    }

    /// <summary>
    /// Resolves the leaf property type for a potentially nested path.
    /// Returns null if the path cannot be fully resolved.
    /// </summary>
    private ITypeSymbol? ResolvePathLeafType(string sourcePath, INamedTypeSymbol sourceType)
    {
        var parts = sourcePath.Split('.');
        ITypeSymbol currentType = sourceType;

        foreach (var part in parts)
        {
            if (currentType is not INamedTypeSymbol namedType)
                return null;

            var prop = GetMappableProperties(namedType).FirstOrDefault(p => p.Name == part);
            if (prop == null)
                return null;

            currentType = prop.Type;
        }

        return currentType;
    }

    private string GenerateForgeIntoMethod(
        IMethodSymbol method,
        ITypeSymbol sourceType,
        INamedTypeSymbol? destinationType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        if (destinationType == null)
            return string.Empty;

        var sourceNamedType = sourceType as INamedTypeSymbol;
        if (sourceNamedType == null)
            return string.Empty;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;
        var destParam = method.Parameters.First(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute")).Name;

        // Get ignored properties from [Ignore] attributes
        var ignoredProperties = GetIgnoredProperties(method);

        // Get property mappings from [ForgeProperty] attributes
        var propertyMappings = GetPropertyMappings(method);

        // Get resolver mappings from [ForgeFrom] attributes
        var resolverMappings = GetResolverMappings(method);

        // Get [ForgeWith] mappings for nested object forging
        var forgeWithMappings = GetForgeWithMappings(method);

        // Method signature
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        sb.AppendLine($"        {accessibility} partial void {method.Name}({sourceType.ToDisplayString()} {sourceParam}, {destinationType.ToDisplayString()} {destParam})");
        sb.AppendLine("        {");

        // Null checks
        sb.AppendLine($"            if ({destParam} == null) throw new global::System.ArgumentNullException(nameof({destParam}));");
        sb.AppendLine($"            if ({sourceParam} == null) return;");
        sb.AppendLine();

        // Get mappable properties
        var sourceProperties = GetMappableProperties(sourceNamedType);
        var destProperties = GetMappableProperties(destinationType).Where(p => p.SetMethod != null);

        foreach (var destProp in destProperties)
        {
            // Skip ignored properties
            if (ignoredProperties.Contains(destProp.Name))
                continue;

            // Check if this property has a resolver from [ForgeFrom]
            if (resolverMappings.TryGetValue(destProp.Name, out var resolverMethodName))
            {
                // Find the source property path for this destination (if mapped via [ForgeProperty])
                string? sourcePropPath = null;
                ITypeSymbol? sourcePathLeafType = null;

                if (propertyMappings.TryGetValue(destProp.Name, out sourcePropPath))
                {
                    // Resolve the leaf type for the full path (handles nested paths like "Customer.Name")
                    sourcePathLeafType = ResolvePathLeafType(sourcePropPath, sourceNamedType);
                }
                else
                {
                    // Try to find by same name
                    var matchingSourceProp = sourceProperties.FirstOrDefault(sp => sp.Name == destProp.Name);
                    if (matchingSourceProp != null)
                    {
                        sourcePropPath = matchingSourceProp.Name;
                        sourcePathLeafType = matchingSourceProp.Type;
                    }
                }

                // Find the resolver method - pass leaf type directly for proper overload selection
                var resolverMethod = FindResolverMethod(forger.Symbol, resolverMethodName, sourceType, sourcePathLeafType);

                if (resolverMethod == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.ResolverMethodNotFound,
                        method.Locations.FirstOrDefault(),
                        resolverMethodName));
                    continue;
                }

                var resolverParamType = resolverMethod.Parameters[0].Type;
                string resolverCall;

                if (SymbolEqualityComparer.Default.Equals(resolverParamType, sourceType) ||
                    CanAssign(sourceType, resolverParamType))
                {
                    resolverCall = $"{resolverMethodName}({sourceParam})";
                }
                else if (sourcePropPath != null && sourcePathLeafType != null &&
                         CanAssign(sourcePathLeafType, resolverParamType))
                {
                    // Pass the source property value - use null-info to handle nullable expressions
                    var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropPath, sourceNamedType);

                    // Handle Nullable<T> to T conversion with explicit cast
                    // Also handle lifted value types from null-conditional (e.g., source.Customer?.Age becomes int?)
                    var isLiftedValueType = hasNullConditional && sourcePathLeafType.IsValueType && GetNullableUnderlyingType(sourcePathLeafType) == null;
                    if (IsNullableToNonNullableValueType(sourcePathLeafType, resolverParamType) || isLiftedValueType)
                    {
                        resolverCall = $"{resolverMethodName}(({resolverParamType.ToDisplayString()}){sourceExpr}!)";
                    }
                    else
                    {
                        // Add null-forgiving if expression is nullable (from null-conditional or nullable ref type)
                        // but resolver param is non-nullable
                        var isNullableExpr = hasNullConditional || sourcePathLeafType.NullableAnnotation == NullableAnnotation.Annotated;
                        var nullForgiving = isNullableExpr && resolverParamType.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                        resolverCall = $"{resolverMethodName}({sourceExpr}{nullForgiving})";
                    }
                }
                else
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidResolverSignature,
                        method.Locations.FirstOrDefault(),
                        resolverMethodName));
                    continue;
                }

                sb.AppendLine($"            {destParam}.{destProp.Name} = {resolverCall};");
                continue;
            }

            // Check if this property has a [ForgeWith] mapping for nested object forging
            if (forgeWithMappings.TryGetValue(destProp.Name, out var forgingMethodName))
            {
                string? forgeWithSourcePropName = null;
                if (propertyMappings.TryGetValue(destProp.Name, out var mappedSource))
                {
                    forgeWithSourcePropName = mappedSource;
                }
                else
                {
                    var matchingSourceProp = sourceProperties.FirstOrDefault(sp =>
                        string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));
                    if (matchingSourceProp != null)
                        forgeWithSourcePropName = matchingSourceProp.Name;
                }

                if (forgeWithSourcePropName != null)
                {
                    var sourcePropertyType = ResolvePathLeafType(forgeWithSourcePropName, sourceNamedType);
                    if (sourcePropertyType != null)
                    {
                        var nestedForgeMethod = FindForgingMethod(forger.Symbol, forgingMethodName, sourcePropertyType, destProp.Type);
                        if (nestedForgeMethod != null)
                        {
                            var (sourceExpr, _) = GenerateSourceExpressionWithNullInfo(sourceParam, forgeWithSourcePropName, sourceNamedType);
                            if (sourcePropertyType.IsReferenceType)
                            {
                                var localVarName = $"__forgeWith_{destProp.Name}";
                                sb.AppendLine($"            if ({sourceExpr} is {{ }} {localVarName})");
                                sb.AppendLine($"                {destParam}.{destProp.Name} = {forgingMethodName}({localVarName});");
                                sb.AppendLine($"            else");
                                sb.AppendLine($"                {destParam}.{destProp.Name} = null;");
                            }
                            else
                            {
                                sb.AppendLine($"            {destParam}.{destProp.Name} = {forgingMethodName}({sourceExpr});");
                            }
                            continue;
                        }
                    }
                }

                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.ResolverMethodNotFound,
                    method.Locations.FirstOrDefault(),
                    forgingMethodName));
                continue;
            }

            // Check if this property has a mapping from [ForgeProperty]
            if (propertyMappings.TryGetValue(destProp.Name, out var sourcePropName))
            {
                var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropName, sourceNamedType);
                // Add null-forgiving operator if we used null-conditional and dest is non-nullable
                var nullForgiving = hasNullConditional && destProp.Type.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                sb.AppendLine($"            {destParam}.{destProp.Name} = {sourceExpr}{nullForgiving};");
                continue;
            }

            var sourceProp = sourceProperties.FirstOrDefault(sp =>
                string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));

            if (sourceProp != null && CanAssign(sourceProp.Type, destProp.Type))
            {
                // Handle Nullable<T> to T conversion using explicit cast which throws if null
                if (IsNullableToNonNullableValueType(sourceProp.Type, destProp.Type))
                {
                    sb.AppendLine($"            {destParam}.{destProp.Name} = ({destProp.Type.ToDisplayString()}){sourceParam}.{sourceProp.Name}!;");
                }
                else
                {
                    sb.AppendLine($"            {destParam}.{destProp.Name} = {sourceParam}.{sourceProp.Name};");
                }
            }
        }

        sb.AppendLine("        }");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a collection forging method (List&lt;T&gt;, T[], IEnumerable&lt;T&gt;, etc.).
    /// </summary>
    private string GenerateCollectionForgeMethod(
        IMethodSymbol method,
        ITypeSymbol sourceCollectionType,
        ITypeSymbol destCollectionType,
        ITypeSymbol sourceElementType,
        ITypeSymbol destElementType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        // Validate that an element forging method exists
        var elementForgeMethod = FindForgingMethod(forger.Symbol, method.Name, sourceElementType, destElementType);
        if (elementForgeMethod == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.ResolverMethodNotFound,
                method.Locations.FirstOrDefault(),
                $"{method.Name}({sourceElementType.ToDisplayString()})"));
            return string.Empty;
        }

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;

        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        var destTypeDisplay = destCollectionType.ToDisplayString();
        var sourceTypeDisplay = sourceCollectionType.ToDisplayString();

        sb.AppendLine($"        {accessibility} partial {destTypeDisplay} {method.Name}({sourceTypeDisplay} {sourceParam})");
        sb.AppendLine("        {");
        sb.AppendLine($"            if ({sourceParam} == null) return null!;");
        sb.AppendLine();

        // Determine the destination collection kind
        if (destCollectionType is IArrayTypeSymbol)
        {
            // T[] target — arrays need count up front; safe because array sources have .Length
            // and list sources have .Count; IEnumerable sources use .Count() (LINQ)
            var destElemDisplay = destElementType.ToDisplayString();
            var lengthExpr = GetCollectionLengthExpression(sourceCollectionType, sourceParam);
            sb.AppendLine($"            var result = new {destElemDisplay}[{lengthExpr}];");
            sb.AppendLine($"            var i = 0;");
            sb.AppendLine($"            foreach (var item in {sourceParam})");
            sb.AppendLine("            {");
            sb.AppendLine($"                result[i++] = {method.Name}(item);");
            sb.AppendLine("            }");
            sb.AppendLine("            return result;");
        }
        else if (destCollectionType is INamedTypeSymbol destNamedType)
        {
            var originalDef = destNamedType.OriginalDefinition.ToDisplayString();

            if (originalDef == "System.Collections.Generic.IEnumerable<T>")
            {
                // IEnumerable<T> - lazy Select projection
                sb.AppendLine($"            return {sourceParam}.Select(item => {method.Name}(item));");
            }
            else
            {
                // List<T>, IList<T>, ICollection<T>, IReadOnlyList<T>, IReadOnlyCollection<T> -> return List<T>
                var destElemDisplay = destElementType.ToDisplayString();

                // Avoid double-enumeration: only pre-size when source has a cheap Count property.
                // For IEnumerable<T> sources, allocate without capacity to avoid calling Count().
                if (HasCheapCount(sourceCollectionType))
                {
                    var countExpr = GetCollectionLengthExpression(sourceCollectionType, sourceParam);
                    sb.AppendLine($"            var result = new global::System.Collections.Generic.List<{destElemDisplay}>({countExpr});");
                }
                else
                {
                    sb.AppendLine($"            var result = new global::System.Collections.Generic.List<{destElemDisplay}>();");
                }

                sb.AppendLine($"            foreach (var item in {sourceParam})");
                sb.AppendLine("            {");
                sb.AppendLine($"                result.Add({method.Name}(item));");
                sb.AppendLine("            }");
                sb.AppendLine("            return result;");
            }
        }

        sb.AppendLine("        }");

        return sb.ToString();
    }

    /// <summary>
    /// Returns true if the collection type has a cheap .Count or .Length property (not LINQ's Count() extension).
    /// </summary>
    private static bool HasCheapCount(ITypeSymbol sourceType)
    {
        if (sourceType is IArrayTypeSymbol)
            return true;

        if (sourceType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var originalDef = namedType.OriginalDefinition.ToDisplayString();
            return originalDef == "System.Collections.Generic.List<T>" ||
                   originalDef == "System.Collections.Generic.ICollection<T>" ||
                   originalDef == "System.Collections.Generic.IReadOnlyCollection<T>" ||
                   originalDef == "System.Collections.Generic.IList<T>" ||
                   originalDef == "System.Collections.Generic.IReadOnlyList<T>";
        }

        return false;
    }

    /// <summary>
    /// Gets the appropriate length/count expression for a collection source type.
    /// </summary>
    private static string GetCollectionLengthExpression(ITypeSymbol sourceType, string sourceParam)
    {
        if (sourceType is IArrayTypeSymbol)
            return $"{sourceParam}.Length";

        if (sourceType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var originalDef = namedType.OriginalDefinition.ToDisplayString();
            // Types with Count property
            if (originalDef == "System.Collections.Generic.List<T>" ||
                originalDef == "System.Collections.Generic.ICollection<T>" ||
                originalDef == "System.Collections.Generic.IReadOnlyCollection<T>" ||
                originalDef == "System.Collections.Generic.IList<T>" ||
                originalDef == "System.Collections.Generic.IReadOnlyList<T>")
            {
                return $"{sourceParam}.Count";
            }
        }

        // Fallback to LINQ Count()
        return $"{sourceParam}.Count()";
    }

    /// <summary>
    /// Gets the element type if the given type is a supported collection type.
    /// Returns null if the type is not a collection.
    /// </summary>
    private ITypeSymbol? GetCollectionElementType(ITypeSymbol type)
    {
        // Handle arrays (T[])
        if (type is IArrayTypeSymbol arrayType)
        {
            return arrayType.ElementType;
        }

        // Handle generic collections
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType && namedType.TypeArguments.Length == 1)
        {
            var originalDef = namedType.OriginalDefinition.ToDisplayString();
            var supportedCollections = new[]
            {
                "System.Collections.Generic.List<T>",
                "System.Collections.Generic.IList<T>",
                "System.Collections.Generic.ICollection<T>",
                "System.Collections.Generic.IEnumerable<T>",
                "System.Collections.Generic.IReadOnlyList<T>",
                "System.Collections.Generic.IReadOnlyCollection<T>"
            };

            if (supportedCollections.Contains(originalDef))
            {
                return namedType.TypeArguments[0];
            }
        }

        return null;
    }

    private static IEnumerable<IPropertySymbol> GetMappableProperties(INamedTypeSymbol? type)
    {
        if (type == null)
            return Enumerable.Empty<IPropertySymbol>();

        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                       !p.IsStatic &&
                       !p.IsIndexer &&
                       p.GetMethod != null);
    }

    private static bool CanAssign(ITypeSymbol source, ITypeSymbol dest)
    {
        // Simple type compatibility check
        if (SymbolEqualityComparer.Default.Equals(source, dest))
            return true;

        // Handle Nullable<T> to T (value types)
        var sourceUnderlying = GetNullableUnderlyingType(source);
        var destUnderlying = GetNullableUnderlyingType(dest);

        if (sourceUnderlying != null && destUnderlying == null)
        {
            // Nullable<T> -> T - allowed but may throw at runtime
            return SymbolEqualityComparer.Default.Equals(sourceUnderlying, dest);
        }

        if (sourceUnderlying == null && destUnderlying != null)
        {
            // T -> Nullable<T> - always allowed
            return SymbolEqualityComparer.Default.Equals(source, destUnderlying);
        }

        // Handle nullable reference types: nullable ref -> non-nullable ref
        if (source.NullableAnnotation == NullableAnnotation.Annotated &&
            dest.NullableAnnotation != NullableAnnotation.Annotated)
        {
            var underlyingSource = source.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            return SymbolEqualityComparer.Default.Equals(underlyingSource, dest);
        }

        // Handle nullable reference types: non-nullable ref -> nullable ref (always valid)
        if (source.NullableAnnotation != NullableAnnotation.Annotated &&
            dest.NullableAnnotation == NullableAnnotation.Annotated)
        {
            var underlyingDest = dest.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            return SymbolEqualityComparer.Default.Equals(source, underlyingDest);
        }

        // Handle inheritance
        var currentType = source;
        while (currentType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(currentType, dest))
                return true;
            currentType = currentType.BaseType;
        }

        // Handle interfaces
        foreach (var iface in source.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, dest))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Gets the underlying type for Nullable&lt;T&gt;, or null if the type is not a nullable value type.
    /// </summary>
    private static ITypeSymbol? GetNullableUnderlyingType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType &&
            namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T &&
            namedType.TypeArguments.Length == 1)
        {
            return namedType.TypeArguments[0];
        }
        return null;
    }

    /// <summary>
    /// Checks if source is Nullable&lt;T&gt; and dest is T.
    /// </summary>
    private static bool IsNullableToNonNullableValueType(ITypeSymbol source, ITypeSymbol dest)
    {
        var sourceUnderlying = GetNullableUnderlyingType(source);
        if (sourceUnderlying == null)
            return false;

        var destUnderlying = GetNullableUnderlyingType(dest);
        if (destUnderlying != null)
            return false;

        return SymbolEqualityComparer.Default.Equals(sourceUnderlying, dest);
    }

    private static string GetAccessibilityKeyword(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private => "private",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
    }
}
