using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace TypeForge.Generator;

/// <summary>
/// Emits generated forging code for TypeForge forger classes.
/// </summary>
internal sealed class ForgeCodeEmitter
{
    private readonly INamedTypeSymbol? _ignoreAttributeSymbol;
    private readonly INamedTypeSymbol? _forgePropertyAttributeSymbol;
    private readonly INamedTypeSymbol? _forgeFromAttributeSymbol;
    private readonly INamedTypeSymbol? _forgeWithAttributeSymbol;

    public ForgeCodeEmitter(Compilation compilation)
    {
        _ignoreAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.IgnoreAttribute");
        _forgePropertyAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.ForgePropertyAttribute");
        _forgeFromAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.ForgeFromAttribute");
        _forgeWithAttributeSymbol = compilation.GetTypeByMetadataName("TypeForge.ForgeWithAttribute");
    }

    public string GenerateForger(ForgerInfo forger, SourceProductionContext context)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        // Namespace
        var ns = forger.Symbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine($"namespace {ns.ToDisplayString()}");
            sb.AppendLine("{");
        }

        // Class declaration with same accessibility
        var accessibility = GetAccessibilityKeyword(forger.Symbol.DeclaredAccessibility);
        sb.AppendLine($"    {accessibility} partial class {forger.Symbol.Name}");
        sb.AppendLine("    {");

        // Find and implement partial methods
        var partialMethods = forger.Symbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.IsPartialDefinition && !m.ReturnsVoid || (m.IsPartialDefinition && m.ReturnsVoid && HasForgeIntoPattern(m)));

        foreach (var method in partialMethods)
        {
            var generatedMethod = GenerateMethod(method, forger, context);
            if (!string.IsNullOrEmpty(generatedMethod))
            {
                sb.AppendLine(generatedMethod);
            }
        }

        sb.AppendLine("    }");

        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static bool HasForgeIntoPattern(IMethodSymbol method)
    {
        // Check if this is a ForgeInto pattern (void return with [UseExistingValue] parameter)
        return method.Parameters.Any(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute" ||
                a.AttributeClass?.ToDisplayString() == "TypeForge.UseExistingValueAttribute"));
    }

    private string GenerateMethod(IMethodSymbol method, ForgerInfo forger, SourceProductionContext context)
    {
        // Validate method has at least one parameter (source)
        if (method.Parameters.Length == 0)
        {
            return string.Empty;
        }

        var sourceType = method.Parameters[0].Type;
        var destinationType = method.ReturnType;

        // Handle ForgeInto pattern
        var useExistingParam = method.Parameters.FirstOrDefault(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute" ||
                a.AttributeClass?.ToDisplayString() == "TypeForge.UseExistingValueAttribute"));

        if (useExistingParam != null)
        {
            destinationType = useExistingParam.Type;
            return GenerateForgeIntoMethod(method, sourceType, destinationType as INamedTypeSymbol, forger, context);
        }

        // Check for enum forging scenarios
        var enumResult = TryGenerateEnumForgeMethod(method, sourceType, destinationType);
        if (enumResult != null)
            return enumResult;

        // Check for collection mapping (List<T>, T[], IEnumerable<T>, etc.)
        var sourceElementType = GetCollectionElementType(sourceType);
        var destElementType = GetCollectionElementType(destinationType);
        if (sourceElementType != null && destElementType != null)
        {
            return GenerateCollectionForgeMethod(method, sourceType, destinationType, sourceElementType, destElementType, forger, context);
        }

        if (destinationType is not INamedTypeSymbol destNamedType)
        {
            return string.Empty;
        }

        return GenerateForgeMethod(method, sourceType as INamedTypeSymbol, destNamedType, forger, context);
    }

    /// <summary>
    /// Tries to generate an enum forging method. Returns null if source/dest are not enum/string combinations.
    /// Handles: enum→enum (cast by name), enum→string (.ToString()), string→enum (Enum.Parse).
    /// </summary>
    private string? TryGenerateEnumForgeMethod(IMethodSymbol method, ITypeSymbol sourceType, ITypeSymbol destinationType)
    {
        var isSourceEnum = sourceType.TypeKind == TypeKind.Enum;
        var isDestEnum = destinationType.TypeKind == TypeKind.Enum;
        var isSourceString = sourceType.SpecialType == SpecialType.System_String;
        var isDestString = destinationType.SpecialType == SpecialType.System_String;

        if (!isSourceEnum && !isDestEnum)
            return null;

        // At least one side must be enum; the other must be enum or string
        if (!isSourceEnum && !isSourceString)
            return null;
        if (!isDestEnum && !isDestString)
            return null;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        var destDisplay = destinationType.ToDisplayString();
        var sourceDisplay = sourceType.ToDisplayString();

        sb.AppendLine($"        {accessibility} partial {destDisplay} {method.Name}({sourceDisplay} {sourceParam})");
        sb.AppendLine("        {");

        if (isSourceEnum && isDestEnum)
        {
            // enum → enum: parse by name for safety (handles mismatched underlying values)
            sb.AppendLine($"            return ({destDisplay})global::System.Enum.Parse(typeof({destDisplay}), {sourceParam}.ToString());");
        }
        else if (isSourceEnum && isDestString)
        {
            // enum → string: .ToString()
            sb.AppendLine($"            return {sourceParam}.ToString();");
        }
        else if (isSourceString && isDestEnum)
        {
            // string → enum: Enum.Parse with case-insensitive matching
            sb.AppendLine($"            return ({destDisplay})global::System.Enum.Parse(typeof({destDisplay}), {sourceParam}, true);");
        }

        sb.AppendLine("        }");
        return sb.ToString();
    }

    private string GenerateForgeMethod(
        IMethodSymbol method,
        INamedTypeSymbol? sourceType,
        INamedTypeSymbol destinationType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        if (sourceType == null)
            return string.Empty;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;

        // Get ignored properties from [Ignore] attributes
        var ignoredProperties = GetIgnoredProperties(method);

        // Get property mappings from [ForgeProperty] attributes
        var propertyMappings = GetPropertyMappings(method);

        // Get resolver mappings from [ForgeFrom] attributes
        var resolverMappings = GetResolverMappings(method);

        // Get [ForgeWith] mappings for nested object forging
        var forgeWithMappings = GetForgeWithMappings(method);

        // Method signature
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        sb.AppendLine($"        {accessibility} partial {destinationType.ToDisplayString()} {method.Name}({sourceType.ToDisplayString()} {sourceParam})");
        sb.AppendLine("        {");

        // Null check
        sb.AppendLine($"            if ({sourceParam} == null) return null!;");
        sb.AppendLine();

        // Get mappable properties
        var sourceProperties = GetMappableProperties(sourceType);
        var destProperties = GetMappableProperties(destinationType);

        // Determine constructor strategy
        var (chosenCtor, ctorParamMappings) = ResolveConstructor(
            destinationType, sourceType, sourceProperties, propertyMappings, context, method);

        // Track which destination properties are covered by constructor parameters
        var ctorCoveredDestProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (ctorParamMappings != null)
        {
            foreach (var mapping in ctorParamMappings)
                ctorCoveredDestProps.Add(mapping.DestPropertyName);
        }

        if (chosenCtor != null && ctorParamMappings != null && chosenCtor.Parameters.Length > 0)
        {
            // Constructor mapping: generate new Dest(param1: expr1, param2: expr2) { Prop = value, ... }
            // Using object initializer syntax so init-only properties work too
            sb.AppendLine($"            var result = new {destinationType.ToDisplayString()}(");

            for (int i = 0; i < ctorParamMappings.Count; i++)
            {
                var mapping = ctorParamMappings[i];
                var separator = i < ctorParamMappings.Count - 1 ? "," : "";
                var expr = GenerateCtorParamExpression(
                    mapping.SourceExpression, mapping.SourcePropertyType, mapping.DestPropertyType);
                sb.AppendLine($"                {mapping.CtorParamName}: {expr}{separator}");
            }

            // Collect remaining property assignments for object initializer
            var remainingDestProps = destProperties
                .Where(p => p.SetMethod != null && !ctorCoveredDestProps.Contains(p.Name))
                .ToList();

            var initAssignments = new List<(string Name, string Expr)>();
            foreach (var destProp in remainingDestProps)
            {
                if (ignoredProperties.Contains(destProp.Name))
                    continue;

                var assignment = GeneratePropertyAssignment(
                    destProp, sourceParam, sourceType, sourceProperties,
                    propertyMappings, resolverMappings, forgeWithMappings, ignoredProperties, forger, context, method);

                if (assignment != null)
                    initAssignments.Add((destProp.Name, assignment));
            }

            if (initAssignments.Count > 0)
            {
                sb.AppendLine("            )");
                sb.AppendLine("            {");
                foreach (var (name, expr) in initAssignments)
                    sb.AppendLine($"                {name} = {expr},");
                sb.AppendLine("            };");
            }
            else
            {
                sb.AppendLine("            );");
            }

            sb.AppendLine("            return result;");
        }
        else
        {
            // Object initializer pattern (existing behavior)
            sb.AppendLine($"            return new {destinationType.ToDisplayString()}");
            sb.AppendLine("            {");

            foreach (var destProp in destProperties)
            {
                var assignment = GeneratePropertyAssignment(
                    destProp, sourceParam, sourceType, sourceProperties,
                    propertyMappings, resolverMappings, forgeWithMappings, ignoredProperties, forger, context, method);

                if (assignment != null)
                    sb.AppendLine($"                {destProp.Name} = {assignment},");
            }

            sb.AppendLine("            };");
        }

        sb.AppendLine("        }");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a property assignment expression string, or null if the property should be skipped.
    /// </summary>
    private string? GeneratePropertyAssignment(
        IPropertySymbol destProp,
        string sourceParam,
        INamedTypeSymbol sourceType,
        IEnumerable<IPropertySymbol> sourceProperties,
        Dictionary<string, string> propertyMappings,
        Dictionary<string, string> resolverMappings,
        Dictionary<string, string> forgeWithMappings,
        HashSet<string> ignoredProperties,
        ForgerInfo forger,
        SourceProductionContext context,
        IMethodSymbol method)
    {
        // Skip ignored properties
        if (ignoredProperties.Contains(destProp.Name))
            return null;

        // Check if this property has a resolver from [ForgeFrom]
        if (resolverMappings.TryGetValue(destProp.Name, out var resolverMethodName))
        {
            return GenerateResolverExpression(
                destProp, resolverMethodName, sourceParam, sourceType,
                sourceProperties, propertyMappings, forger, context, method);
        }

        // Check if this property has a [ForgeWith] mapping for nested object forging
        if (forgeWithMappings.TryGetValue(destProp.Name, out var forgingMethodName))
        {
            return GenerateForgeWithExpression(
                destProp, forgingMethodName, sourceParam, sourceType,
                sourceProperties, propertyMappings, forger, context, method);
        }

        // Check if this property has a mapping from [ForgeProperty]
        if (propertyMappings.TryGetValue(destProp.Name, out var sourcePropName))
        {
            var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropName, sourceType);
            var nullForgiving = hasNullConditional && destProp.Type.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
            return $"{sourceExpr}{nullForgiving}";
        }

        // Try to find matching source property by name (convention)
        var sourceProp = sourceProperties.FirstOrDefault(sp =>
            string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));

        if (sourceProp != null && CanAssign(sourceProp.Type, destProp.Type))
        {
            if (IsNullableToNonNullableValueType(sourceProp.Type, destProp.Type))
                return $"({destProp.Type.ToDisplayString()}){sourceParam}.{sourceProp.Name}!";
            else
                return $"{sourceParam}.{sourceProp.Name}";
        }

        // Try automatic flattening: destProp "CustomerName" → source.Customer.Name
        var flattenResult = TryAutoFlatten(destProp, sourceParam, sourceType);
        if (flattenResult != null)
            return flattenResult;

        return null;
    }

    /// <summary>
    /// Generates a resolver expression for [ForgeFrom].
    /// </summary>
    private string? GenerateResolverExpression(
        IPropertySymbol destProp,
        string resolverMethodName,
        string sourceParam,
        INamedTypeSymbol sourceType,
        IEnumerable<IPropertySymbol> sourceProperties,
        Dictionary<string, string> propertyMappings,
        ForgerInfo forger,
        SourceProductionContext context,
        IMethodSymbol method)
    {
        string? sourcePropPath = null;
        ITypeSymbol? sourcePathLeafType = null;

        if (propertyMappings.TryGetValue(destProp.Name, out sourcePropPath))
        {
            sourcePathLeafType = ResolvePathLeafType(sourcePropPath, sourceType);
        }
        else
        {
            var matchingSourceProp = sourceProperties.FirstOrDefault(sp => sp.Name == destProp.Name);
            if (matchingSourceProp != null)
            {
                sourcePropPath = matchingSourceProp.Name;
                sourcePathLeafType = matchingSourceProp.Type;
            }
        }

        var resolverMethod = FindResolverMethod(forger.Symbol, resolverMethodName, sourceType, sourcePathLeafType);

        if (resolverMethod == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.ResolverMethodNotFound,
                method.Locations.FirstOrDefault(),
                resolverMethodName));
            return null;
        }

        var resolverParamType = resolverMethod.Parameters[0].Type;

        if (SymbolEqualityComparer.Default.Equals(resolverParamType, sourceType) ||
            CanAssign(sourceType, resolverParamType))
        {
            return $"{resolverMethodName}({sourceParam})";
        }
        else if (sourcePropPath != null && sourcePathLeafType != null &&
                 CanAssign(sourcePathLeafType, resolverParamType))
        {
            var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropPath, sourceType);
            var isLiftedValueType = hasNullConditional && sourcePathLeafType.IsValueType && GetNullableUnderlyingType(sourcePathLeafType) == null;
            if (IsNullableToNonNullableValueType(sourcePathLeafType, resolverParamType) || isLiftedValueType)
            {
                return $"{resolverMethodName}(({resolverParamType.ToDisplayString()}){sourceExpr}!)";
            }
            else
            {
                var isNullableExpr = hasNullConditional || sourcePathLeafType.NullableAnnotation == NullableAnnotation.Annotated;
                var nullForgiving = isNullableExpr && resolverParamType.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                return $"{resolverMethodName}({sourceExpr}{nullForgiving})";
            }
        }
        else
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidResolverSignature,
                method.Locations.FirstOrDefault(),
                resolverMethodName));
            return null;
        }
    }

    /// <summary>
    /// Generates a [ForgeWith] expression for nested object forging.
    /// </summary>
    private string? GenerateForgeWithExpression(
        IPropertySymbol destProp,
        string forgingMethodName,
        string sourceParam,
        INamedTypeSymbol sourceType,
        IEnumerable<IPropertySymbol> sourceProperties,
        Dictionary<string, string> propertyMappings,
        ForgerInfo forger,
        SourceProductionContext context,
        IMethodSymbol method)
    {
        string? forgeWithSourcePropName = null;
        if (propertyMappings.TryGetValue(destProp.Name, out var mappedSource))
        {
            forgeWithSourcePropName = mappedSource;
        }
        else
        {
            var matchingSourceProp = sourceProperties.FirstOrDefault(sp =>
                string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));
            if (matchingSourceProp != null)
                forgeWithSourcePropName = matchingSourceProp.Name;
        }

        if (forgeWithSourcePropName != null)
        {
            var sourcePropertyType = ResolvePathLeafType(forgeWithSourcePropName, sourceType);
            if (sourcePropertyType != null)
            {
                var nestedForgeMethod = FindForgingMethod(forger.Symbol, forgingMethodName, sourcePropertyType, destProp.Type);
                if (nestedForgeMethod != null)
                {
                    var (sourceExpr, _) = GenerateSourceExpressionWithNullInfo(sourceParam, forgeWithSourcePropName, sourceType);
                    if (sourcePropertyType.IsReferenceType)
                    {
                        var localVarName = $"__forgeWith_{destProp.Name}";
                        return $"{sourceExpr} is {{ }} {localVarName} ? {forgingMethodName}({localVarName}) : null!";
                    }
                    else
                    {
                        return $"{forgingMethodName}({sourceExpr})";
                    }
                }
            }
        }

        context.ReportDiagnostic(Diagnostic.Create(
            DiagnosticDescriptors.ResolverMethodNotFound,
            method.Locations.FirstOrDefault(),
            forgingMethodName));
        return null;
    }

    /// <summary>
    /// Generates a mapping expression for a constructor parameter, handling Nullable&lt;T&gt; to T.
    /// </summary>
    private static string GenerateCtorParamExpression(
        string sourceExpression,
        ITypeSymbol? sourcePropertyType,
        ITypeSymbol destPropertyType)
    {
        if (sourcePropertyType != null && IsNullableToNonNullableValueType(sourcePropertyType, destPropertyType))
            return $"({destPropertyType.ToDisplayString()}){sourceExpression}!";

        return sourceExpression;
    }

    /// <summary>
    /// Tries automatic flattening: matches dest property "CustomerName" to source path "Customer.Name".
    /// Walks the source type hierarchy looking for concatenated property name matches.
    /// </summary>
    private string? TryAutoFlatten(IPropertySymbol destProp, string sourceParam, INamedTypeSymbol sourceType)
    {
        var destName = destProp.Name;
        var (expr, leafType) = TryAutoFlattenRecursive(destName, 0, sourceParam, sourceType);
        if (expr == null || leafType == null)
            return null;

        // Validate type compatibility between leaf and destination property
        if (!CanAssign(leafType, destProp.Type))
            return null;

        // Handle nullable-to-non-nullable value type conversion
        if (IsNullableToNonNullableValueType(leafType, destProp.Type))
            return $"({destProp.Type.ToDisplayString()}){expr}";

        return expr;
    }

    private (string? Expression, ITypeSymbol? LeafType) TryAutoFlattenRecursive(string destName, int startIndex, string currentExpr, INamedTypeSymbol currentType)
    {
        if (startIndex >= destName.Length)
            return (null, null);

        var properties = GetMappableProperties(currentType).ToList();

        foreach (var prop in properties)
        {
            var propName = prop.Name;
            if (destName.Length >= startIndex + propName.Length &&
                string.Equals(destName.Substring(startIndex, propName.Length), propName, StringComparison.OrdinalIgnoreCase))
            {
                var newStartIndex = startIndex + propName.Length;

                if (newStartIndex == destName.Length)
                {
                    // Full match - this property is the leaf
                    string leafExpr;
                    if (prop.Type.IsReferenceType)
                        leafExpr = $"{currentExpr}?.{propName}!";
                    else if (currentExpr.Contains("?."))
                        leafExpr = $"{currentExpr}?.{propName}!";
                    else
                        leafExpr = $"{currentExpr}.{propName}";
                    return (leafExpr, prop.Type);
                }

                // Partial match - recurse into this property's type
                if (prop.Type is INamedTypeSymbol namedType && namedType.TypeKind == TypeKind.Class)
                {
                    var nullConditionalExpr = prop.Type.IsReferenceType
                        ? $"{currentExpr}?.{propName}"
                        : $"{currentExpr}.{propName}";
                    var result = TryAutoFlattenRecursive(destName, newStartIndex, nullConditionalExpr, namedType);
                    if (result.Expression != null)
                        return result;
                }
            }
        }

        return (null, null);
    }

    /// <summary>
    /// Resolves the constructor to use for destination type instantiation.
    /// Returns (null, null) if a parameterless constructor should be used (object initializer pattern).
    /// </summary>
    private (IMethodSymbol? Constructor, List<CtorParamMapping>? Mappings) ResolveConstructor(
        INamedTypeSymbol destinationType,
        INamedTypeSymbol sourceType,
        IEnumerable<IPropertySymbol> sourceProperties,
        Dictionary<string, string> propertyMappings,
        SourceProductionContext context,
        IMethodSymbol method)
    {
        var constructors = destinationType.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .ToList();

        // If a parameterless constructor exists, prefer it (object initializer pattern)
        var parameterlessCtor = constructors.FirstOrDefault(c => c.Parameters.Length == 0);
        if (parameterlessCtor != null)
            return (null, null);

        if (constructors.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.DestinationTypeHasNoConstructor,
                method.Locations.FirstOrDefault(),
                destinationType.Name));
            return (null, null);
        }

        // Build a reverse map: dest property name → source expression
        var destToSourceExpr = BuildDestToSourceMap(sourceType, sourceProperties.ToList(), propertyMappings);
        var sourcePropertiesList = sourceProperties.ToList();

        // Score each constructor by how many parameters can be satisfied
        var scoredCtors = new List<(IMethodSymbol Ctor, List<CtorParamMapping> Mappings, int Score)>();

        foreach (var ctor in constructors)
        {
            var mappings = new List<CtorParamMapping>();
            var allMatched = true;

            foreach (var param in ctor.Parameters)
            {
                var paramName = param.Name;

                // Try case-insensitive match against destination property names first
                // (constructor parameter matching is always case-insensitive per spec)
                string? matchedDestPropName = null;
                string? sourceExpr = null;
                ITypeSymbol? sourcePropType = null;

                // Check if any dest prop matches this ctor param (case-insensitive)
                foreach (var kvp in destToSourceExpr)
                {
                    if (string.Equals(kvp.Key, paramName, StringComparison.OrdinalIgnoreCase))
                    {
                        matchedDestPropName = kvp.Key;
                        sourceExpr = kvp.Value.Expression;
                        sourcePropType = kvp.Value.Type;
                        break;
                    }
                }

                // Also try direct source property match (case-insensitive)
                if (sourceExpr == null)
                {
                    var directMatch = sourcePropertiesList.FirstOrDefault(sp =>
                        string.Equals(sp.Name, paramName, StringComparison.OrdinalIgnoreCase));
                    if (directMatch != null)
                    {
                        matchedDestPropName = paramName;
                        sourceExpr = $"source.{directMatch.Name}";
                        sourcePropType = directMatch.Type;
                    }
                }

                if (sourceExpr != null && sourcePropType != null && CanAssign(sourcePropType, param.Type))
                {
                    mappings.Add(new CtorParamMapping(param.Name, matchedDestPropName!, sourceExpr, sourcePropType, param.Type));
                }
                else
                {
                    allMatched = false;
                    break;
                }
            }

            if (allMatched)
            {
                scoredCtors.Add((ctor, mappings, ctor.Parameters.Length));
            }
        }

        if (scoredCtors.Count == 0)
        {
            // No fully-matched ctor. Report TF0014 for the constructor with the most params.
            var bestCtor = constructors.OrderByDescending(c => c.Parameters.Length).First();
            foreach (var param in bestCtor.Parameters)
            {
                var found = destToSourceExpr.Keys.Any(k => string.Equals(k, param.Name, StringComparison.OrdinalIgnoreCase))
                    || sourcePropertiesList.Any(sp => string.Equals(sp.Name, param.Name, StringComparison.OrdinalIgnoreCase));
                if (!found)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.ConstructorParameterNotMatched,
                        method.Locations.FirstOrDefault(),
                        param.Name,
                        destinationType.Name));
                }
            }
            return (null, null);
        }

        // Pick best (most parameters matched)
        var maxScore = scoredCtors.Max(s => s.Score);
        var bestMatches = scoredCtors.Where(s => s.Score == maxScore).ToList();

        if (bestMatches.Count > 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.AmbiguousConstructor,
                method.Locations.FirstOrDefault(),
                destinationType.Name));
            return (null, null);
        }

        return (bestMatches[0].Ctor, bestMatches[0].Mappings);
    }

    /// <summary>
    /// Builds a mapping from destination property name → source expression info.
    /// Includes [ForgeProperty] mappings and direct name matches.
    /// </summary>
    private Dictionary<string, (string Expression, ITypeSymbol? Type)> BuildDestToSourceMap(
        INamedTypeSymbol sourceType,
        List<IPropertySymbol> sourceProperties,
        Dictionary<string, string> propertyMappings)
    {
        var map = new Dictionary<string, (string Expression, ITypeSymbol? Type)>(StringComparer.OrdinalIgnoreCase);

        // Add all direct source property matches by name
        foreach (var sp in sourceProperties)
        {
            map[sp.Name] = ($"source.{sp.Name}", sp.Type);
        }

        // Overlay [ForgeProperty] mappings (dest name → source path)
        foreach (var kvp in propertyMappings)
        {
            var destPropName = kvp.Key;
            var sourcePath = kvp.Value;
            var leafType = ResolvePathLeafType(sourcePath, sourceType);

            if (sourcePath.Contains("."))
            {
                var (expr, _) = GenerateSourceExpressionWithNullInfo("source", sourcePath, sourceType);
                map[destPropName] = (expr, leafType);
            }
            else
            {
                map[destPropName] = ($"source.{sourcePath}", leafType);
            }
        }

        return map;
    }

    private sealed class CtorParamMapping
    {
        public CtorParamMapping(string ctorParamName, string destPropertyName, string sourceExpression, ITypeSymbol? sourcePropertyType, ITypeSymbol destPropertyType)
        {
            CtorParamName = ctorParamName;
            DestPropertyName = destPropertyName;
            SourceExpression = sourceExpression;
            SourcePropertyType = sourcePropertyType;
            DestPropertyType = destPropertyType;
        }

        public string CtorParamName { get; }
        public string DestPropertyName { get; }
        public string SourceExpression { get; }
        public ITypeSymbol? SourcePropertyType { get; }
        public ITypeSymbol DestPropertyType { get; }
    }

    private HashSet<string> GetIgnoredProperties(IMethodSymbol method)
    {
        var ignored = new HashSet<string>(StringComparer.Ordinal);

        if (_ignoreAttributeSymbol == null)
            return ignored;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _ignoreAttributeSymbol))
                continue;

            // The [Ignore] attribute takes params string[] propertyNames
            if (attr.ConstructorArguments.Length > 0)
            {
                var arg = attr.ConstructorArguments[0];
                if (arg.Kind == TypedConstantKind.Array)
                {
                    foreach (var item in arg.Values)
                    {
                        if (item.Value is string propName)
                        {
                            ignored.Add(propName);
                        }
                    }
                }
            }
        }

        return ignored;
    }

    /// <summary>
    /// Gets property mappings from [ForgeProperty] attributes.
    /// Returns a dictionary mapping destination property name to source property path.
    /// </summary>
    private Dictionary<string, string> GetPropertyMappings(IMethodSymbol method)
    {
        var mappings = new Dictionary<string, string>(StringComparer.Ordinal);

        if (_forgePropertyAttributeSymbol == null)
            return mappings;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _forgePropertyAttributeSymbol))
                continue;

            // [ForgeProperty(sourceProperty, destinationProperty)]
            if (attr.ConstructorArguments.Length >= 2)
            {
                var sourceProperty = attr.ConstructorArguments[0].Value as string;
                var destinationProperty = attr.ConstructorArguments[1].Value as string;

                if (!string.IsNullOrEmpty(sourceProperty) && !string.IsNullOrEmpty(destinationProperty))
                {
                    mappings[destinationProperty!] = sourceProperty!;
                }
            }
        }

        return mappings;
    }

    /// <summary>
    /// Gets resolver mappings from [ForgeFrom] attributes.
    /// Returns a dictionary mapping destination property name to resolver method name.
    /// </summary>
    private Dictionary<string, string> GetResolverMappings(IMethodSymbol method)
    {
        var resolvers = new Dictionary<string, string>(StringComparer.Ordinal);

        if (_forgeFromAttributeSymbol == null)
            return resolvers;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _forgeFromAttributeSymbol))
                continue;

            // [ForgeFrom(destinationProperty, resolverMethodName)]
            if (attr.ConstructorArguments.Length >= 2)
            {
                var destinationProperty = attr.ConstructorArguments[0].Value as string;
                var resolverMethodName = attr.ConstructorArguments[1].Value as string;

                if (!string.IsNullOrEmpty(destinationProperty) && !string.IsNullOrEmpty(resolverMethodName))
                {
                    resolvers[destinationProperty!] = resolverMethodName!;
                }
            }
        }

        return resolvers;
    }

    /// <summary>
    /// Gets [ForgeWith] mappings.
    /// Returns a dictionary mapping destination property name to forging method name.
    /// </summary>
    private Dictionary<string, string> GetForgeWithMappings(IMethodSymbol method)
    {
        var mappings = new Dictionary<string, string>(StringComparer.Ordinal);

        if (_forgeWithAttributeSymbol == null)
            return mappings;

        foreach (var attr in method.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, _forgeWithAttributeSymbol))
                continue;

            // [ForgeWith(destinationProperty, forgingMethodName)]
            if (attr.ConstructorArguments.Length >= 2)
            {
                var destinationProperty = attr.ConstructorArguments[0].Value as string;
                var forgingMethodName = attr.ConstructorArguments[1].Value as string;

                if (!string.IsNullOrEmpty(destinationProperty) && !string.IsNullOrEmpty(forgingMethodName))
                {
                    mappings[destinationProperty!] = forgingMethodName!;
                }
            }
        }

        return mappings;
    }

    /// <summary>
    /// Finds a forging method on the forger class that accepts the given source type and returns the given destination type.
    /// </summary>
    private static IMethodSymbol? FindForgingMethod(INamedTypeSymbol forgerType, string methodName, ITypeSymbol sourcePropertyType, ITypeSymbol destPropertyType)
    {
        return forgerType.GetMembers(methodName)
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.IsPartialDefinition &&
                m.Parameters.Length == 1 &&
                !m.ReturnsVoid &&
                SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, sourcePropertyType) &&
                SymbolEqualityComparer.Default.Equals(m.ReturnType, destPropertyType));
    }

    /// <summary>
    /// Finds a resolver method in the forger class.
    /// Prefers exact type matches over assignable matches for deterministic overload selection.
    /// </summary>
    private IMethodSymbol? FindResolverMethod(INamedTypeSymbol forgerType, string methodName, ITypeSymbol sourceType, ITypeSymbol? preferredParamType)
    {
        var candidates = forgerType.GetMembers(methodName)
            .OfType<IMethodSymbol>()
            .Where(m => !m.ReturnsVoid && m.Parameters.Length == 1)
            .ToList();

        if (candidates.Count == 0)
            return null;

        // Prefer Method(TPreferredType) if preferredParamType is provided
        if (preferredParamType != null)
        {
            // First try exact match
            var exactMatch = candidates.FirstOrDefault(m =>
                SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, preferredParamType));
            if (exactMatch != null)
                return exactMatch;

            // Then try assignable match
            var assignableMatch = candidates.FirstOrDefault(m =>
                CanAssign(preferredParamType, m.Parameters[0].Type));
            if (assignableMatch != null)
                return assignableMatch;
        }

        // Fall back to Method(TSource) - prefer exact match first
        var exactSourceMatch = candidates.FirstOrDefault(m =>
            SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, sourceType));
        if (exactSourceMatch != null)
            return exactSourceMatch;

        var assignableSourceMatch = candidates.FirstOrDefault(m =>
            CanAssign(sourceType, m.Parameters[0].Type));

        return assignableSourceMatch ?? candidates.FirstOrDefault();
    }

    /// <summary>
    /// Generates the source expression for a property, handling nested paths.
    /// Returns a tuple of (expression, hasNullConditional).
    /// </summary>
    private (string Expression, bool HasNullConditional) GenerateSourceExpressionWithNullInfo(string sourceParam, string sourcePath, INamedTypeSymbol sourceType)
    {
        if (!sourcePath.Contains("."))
        {
            return ($"{sourceParam}.{sourcePath}", false);
        }

        // Handle nested path (e.g., "Customer.Name")
        var parts = sourcePath.Split('.');
        var expression = new StringBuilder(sourceParam);
        var currentType = sourceType;
        var hasNullConditional = false;

        for (int i = 0; i < parts.Length; i++)
        {
            var part = parts[i];
            var prop = GetMappableProperties(currentType).FirstOrDefault(p => p.Name == part);

            if (prop == null)
            {
                // Property not found, just append directly
                expression.Append($".{part}");
                continue;
            }

            // Add null-conditional for reference types (except the last property)
            if (i < parts.Length - 1 && prop.Type.IsReferenceType)
            {
                expression.Append($".{part}?");
                hasNullConditional = true;
            }
            else
            {
                expression.Append($".{part}");
            }

            if (prop.Type is INamedTypeSymbol namedType)
            {
                currentType = namedType;
            }
        }

        return (expression.ToString(), hasNullConditional);
    }

    /// <summary>
    /// Resolves the leaf property type for a potentially nested path.
    /// Returns null if the path cannot be fully resolved.
    /// </summary>
    private ITypeSymbol? ResolvePathLeafType(string sourcePath, INamedTypeSymbol sourceType)
    {
        var parts = sourcePath.Split('.');
        ITypeSymbol currentType = sourceType;

        foreach (var part in parts)
        {
            if (currentType is not INamedTypeSymbol namedType)
                return null;

            var prop = GetMappableProperties(namedType).FirstOrDefault(p => p.Name == part);
            if (prop == null)
                return null;

            currentType = prop.Type;
        }

        return currentType;
    }

    private string GenerateForgeIntoMethod(
        IMethodSymbol method,
        ITypeSymbol sourceType,
        INamedTypeSymbol? destinationType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        if (destinationType == null)
            return string.Empty;

        var sourceNamedType = sourceType as INamedTypeSymbol;
        if (sourceNamedType == null)
            return string.Empty;

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;
        var destParam = method.Parameters.First(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.Name == "UseExistingValueAttribute")).Name;

        // Get ignored properties from [Ignore] attributes
        var ignoredProperties = GetIgnoredProperties(method);

        // Get property mappings from [ForgeProperty] attributes
        var propertyMappings = GetPropertyMappings(method);

        // Get resolver mappings from [ForgeFrom] attributes
        var resolverMappings = GetResolverMappings(method);

        // Get [ForgeWith] mappings for nested object forging
        var forgeWithMappings = GetForgeWithMappings(method);

        // Method signature
        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        sb.AppendLine($"        {accessibility} partial void {method.Name}({sourceType.ToDisplayString()} {sourceParam}, {destinationType.ToDisplayString()} {destParam})");
        sb.AppendLine("        {");

        // Null checks
        sb.AppendLine($"            if ({destParam} == null) throw new global::System.ArgumentNullException(nameof({destParam}));");
        sb.AppendLine($"            if ({sourceParam} == null) return;");
        sb.AppendLine();

        // Get mappable properties
        var sourceProperties = GetMappableProperties(sourceNamedType);
        var destProperties = GetMappableProperties(destinationType).Where(p => p.SetMethod != null);

        foreach (var destProp in destProperties)
        {
            // Skip ignored properties
            if (ignoredProperties.Contains(destProp.Name))
                continue;

            // Check if this property has a resolver from [ForgeFrom]
            if (resolverMappings.TryGetValue(destProp.Name, out var resolverMethodName))
            {
                // Find the source property path for this destination (if mapped via [ForgeProperty])
                string? sourcePropPath = null;
                ITypeSymbol? sourcePathLeafType = null;

                if (propertyMappings.TryGetValue(destProp.Name, out sourcePropPath))
                {
                    // Resolve the leaf type for the full path (handles nested paths like "Customer.Name")
                    sourcePathLeafType = ResolvePathLeafType(sourcePropPath, sourceNamedType);
                }
                else
                {
                    // Try to find by same name
                    var matchingSourceProp = sourceProperties.FirstOrDefault(sp => sp.Name == destProp.Name);
                    if (matchingSourceProp != null)
                    {
                        sourcePropPath = matchingSourceProp.Name;
                        sourcePathLeafType = matchingSourceProp.Type;
                    }
                }

                // Find the resolver method - pass leaf type directly for proper overload selection
                var resolverMethod = FindResolverMethod(forger.Symbol, resolverMethodName, sourceType, sourcePathLeafType);

                if (resolverMethod == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.ResolverMethodNotFound,
                        method.Locations.FirstOrDefault(),
                        resolverMethodName));
                    continue;
                }

                var resolverParamType = resolverMethod.Parameters[0].Type;
                string resolverCall;

                if (SymbolEqualityComparer.Default.Equals(resolverParamType, sourceType) ||
                    CanAssign(sourceType, resolverParamType))
                {
                    resolverCall = $"{resolverMethodName}({sourceParam})";
                }
                else if (sourcePropPath != null && sourcePathLeafType != null &&
                         CanAssign(sourcePathLeafType, resolverParamType))
                {
                    // Pass the source property value - use null-info to handle nullable expressions
                    var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropPath, sourceNamedType);

                    // Handle Nullable<T> to T conversion with explicit cast
                    // Also handle lifted value types from null-conditional (e.g., source.Customer?.Age becomes int?)
                    var isLiftedValueType = hasNullConditional && sourcePathLeafType.IsValueType && GetNullableUnderlyingType(sourcePathLeafType) == null;
                    if (IsNullableToNonNullableValueType(sourcePathLeafType, resolverParamType) || isLiftedValueType)
                    {
                        resolverCall = $"{resolverMethodName}(({resolverParamType.ToDisplayString()}){sourceExpr}!)";
                    }
                    else
                    {
                        // Add null-forgiving if expression is nullable (from null-conditional or nullable ref type)
                        // but resolver param is non-nullable
                        var isNullableExpr = hasNullConditional || sourcePathLeafType.NullableAnnotation == NullableAnnotation.Annotated;
                        var nullForgiving = isNullableExpr && resolverParamType.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                        resolverCall = $"{resolverMethodName}({sourceExpr}{nullForgiving})";
                    }
                }
                else
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.InvalidResolverSignature,
                        method.Locations.FirstOrDefault(),
                        resolverMethodName));
                    continue;
                }

                sb.AppendLine($"            {destParam}.{destProp.Name} = {resolverCall};");
                continue;
            }

            // Check if this property has a [ForgeWith] mapping for nested object forging
            if (forgeWithMappings.TryGetValue(destProp.Name, out var forgingMethodName))
            {
                string? forgeWithSourcePropName = null;
                if (propertyMappings.TryGetValue(destProp.Name, out var mappedSource))
                {
                    forgeWithSourcePropName = mappedSource;
                }
                else
                {
                    var matchingSourceProp = sourceProperties.FirstOrDefault(sp =>
                        string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));
                    if (matchingSourceProp != null)
                        forgeWithSourcePropName = matchingSourceProp.Name;
                }

                if (forgeWithSourcePropName != null)
                {
                    var sourcePropertyType = ResolvePathLeafType(forgeWithSourcePropName, sourceNamedType);
                    if (sourcePropertyType != null)
                    {
                        var nestedForgeMethod = FindForgingMethod(forger.Symbol, forgingMethodName, sourcePropertyType, destProp.Type);
                        if (nestedForgeMethod != null)
                        {
                            var (sourceExpr, _) = GenerateSourceExpressionWithNullInfo(sourceParam, forgeWithSourcePropName, sourceNamedType);
                            if (sourcePropertyType.IsReferenceType)
                            {
                                var localVarName = $"__forgeWith_{destProp.Name}";
                                sb.AppendLine($"            if ({sourceExpr} is {{ }} {localVarName})");
                                sb.AppendLine($"                {destParam}.{destProp.Name} = {forgingMethodName}({localVarName});");
                                sb.AppendLine($"            else");
                                sb.AppendLine($"                {destParam}.{destProp.Name} = null;");
                            }
                            else
                            {
                                sb.AppendLine($"            {destParam}.{destProp.Name} = {forgingMethodName}({sourceExpr});");
                            }
                            continue;
                        }
                    }
                }

                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.ResolverMethodNotFound,
                    method.Locations.FirstOrDefault(),
                    forgingMethodName));
                continue;
            }

            // Check if this property has a mapping from [ForgeProperty]
            if (propertyMappings.TryGetValue(destProp.Name, out var sourcePropName))
            {
                var (sourceExpr, hasNullConditional) = GenerateSourceExpressionWithNullInfo(sourceParam, sourcePropName, sourceNamedType);
                // Add null-forgiving operator if we used null-conditional and dest is non-nullable
                var nullForgiving = hasNullConditional && destProp.Type.NullableAnnotation != NullableAnnotation.Annotated ? "!" : "";
                sb.AppendLine($"            {destParam}.{destProp.Name} = {sourceExpr}{nullForgiving};");
                continue;
            }

            var sourceProp = sourceProperties.FirstOrDefault(sp =>
                string.Equals(sp.Name, destProp.Name, StringComparison.Ordinal));

            if (sourceProp != null && CanAssign(sourceProp.Type, destProp.Type))
            {
                // Handle Nullable<T> to T conversion using explicit cast which throws if null
                if (IsNullableToNonNullableValueType(sourceProp.Type, destProp.Type))
                {
                    sb.AppendLine($"            {destParam}.{destProp.Name} = ({destProp.Type.ToDisplayString()}){sourceParam}.{sourceProp.Name}!;");
                }
                else
                {
                    sb.AppendLine($"            {destParam}.{destProp.Name} = {sourceParam}.{sourceProp.Name};");
                }
            }
        }

        sb.AppendLine("        }");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a collection forging method (List&lt;T&gt;, T[], IEnumerable&lt;T&gt;, etc.).
    /// </summary>
    private string GenerateCollectionForgeMethod(
        IMethodSymbol method,
        ITypeSymbol sourceCollectionType,
        ITypeSymbol destCollectionType,
        ITypeSymbol sourceElementType,
        ITypeSymbol destElementType,
        ForgerInfo forger,
        SourceProductionContext context)
    {
        // Validate that an element forging method exists
        var elementForgeMethod = FindForgingMethod(forger.Symbol, method.Name, sourceElementType, destElementType);
        if (elementForgeMethod == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.ResolverMethodNotFound,
                method.Locations.FirstOrDefault(),
                $"{method.Name}({sourceElementType.ToDisplayString()})"));
            return string.Empty;
        }

        var sb = new StringBuilder();
        var sourceParam = method.Parameters[0].Name;

        var accessibility = GetAccessibilityKeyword(method.DeclaredAccessibility);
        var destTypeDisplay = destCollectionType.ToDisplayString();
        var sourceTypeDisplay = sourceCollectionType.ToDisplayString();

        sb.AppendLine($"        {accessibility} partial {destTypeDisplay} {method.Name}({sourceTypeDisplay} {sourceParam})");
        sb.AppendLine("        {");
        sb.AppendLine($"            if ({sourceParam} == null) return null!;");
        sb.AppendLine();

        // Determine the destination collection kind
        if (destCollectionType is IArrayTypeSymbol)
        {
            // T[] target — arrays need count up front; safe because array sources have .Length
            // and list sources have .Count; IEnumerable sources use .Count() (LINQ)
            var destElemDisplay = destElementType.ToDisplayString();
            var lengthExpr = GetCollectionLengthExpression(sourceCollectionType, sourceParam);
            sb.AppendLine($"            var result = new {destElemDisplay}[{lengthExpr}];");
            sb.AppendLine($"            var i = 0;");
            sb.AppendLine($"            foreach (var item in {sourceParam})");
            sb.AppendLine("            {");
            sb.AppendLine($"                result[i++] = {method.Name}(item);");
            sb.AppendLine("            }");
            sb.AppendLine("            return result;");
        }
        else if (destCollectionType is INamedTypeSymbol destNamedType)
        {
            var originalDef = destNamedType.OriginalDefinition.ToDisplayString();

            if (originalDef == "System.Collections.Generic.IEnumerable<T>")
            {
                // IEnumerable<T> - lazy Select projection
                sb.AppendLine($"            return {sourceParam}.Select(item => {method.Name}(item));");
            }
            else
            {
                // List<T>, IList<T>, ICollection<T>, IReadOnlyList<T>, IReadOnlyCollection<T> -> return List<T>
                var destElemDisplay = destElementType.ToDisplayString();

                // Avoid double-enumeration: only pre-size when source has a cheap Count property.
                // For IEnumerable<T> sources, allocate without capacity to avoid calling Count().
                if (HasCheapCount(sourceCollectionType))
                {
                    var countExpr = GetCollectionLengthExpression(sourceCollectionType, sourceParam);
                    sb.AppendLine($"            var result = new global::System.Collections.Generic.List<{destElemDisplay}>({countExpr});");
                }
                else
                {
                    sb.AppendLine($"            var result = new global::System.Collections.Generic.List<{destElemDisplay}>();");
                }

                sb.AppendLine($"            foreach (var item in {sourceParam})");
                sb.AppendLine("            {");
                sb.AppendLine($"                result.Add({method.Name}(item));");
                sb.AppendLine("            }");
                sb.AppendLine("            return result;");
            }
        }

        sb.AppendLine("        }");

        return sb.ToString();
    }

    /// <summary>
    /// Returns true if the collection type has a cheap .Count or .Length property (not LINQ's Count() extension).
    /// </summary>
    private static bool HasCheapCount(ITypeSymbol sourceType)
    {
        if (sourceType is IArrayTypeSymbol)
            return true;

        if (sourceType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var originalDef = namedType.OriginalDefinition.ToDisplayString();
            return originalDef == "System.Collections.Generic.List<T>" ||
                   originalDef == "System.Collections.Generic.ICollection<T>" ||
                   originalDef == "System.Collections.Generic.IReadOnlyCollection<T>" ||
                   originalDef == "System.Collections.Generic.IList<T>" ||
                   originalDef == "System.Collections.Generic.IReadOnlyList<T>";
        }

        return false;
    }

    /// <summary>
    /// Gets the appropriate length/count expression for a collection source type.
    /// </summary>
    private static string GetCollectionLengthExpression(ITypeSymbol sourceType, string sourceParam)
    {
        if (sourceType is IArrayTypeSymbol)
            return $"{sourceParam}.Length";

        if (sourceType is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var originalDef = namedType.OriginalDefinition.ToDisplayString();
            // Types with Count property
            if (originalDef == "System.Collections.Generic.List<T>" ||
                originalDef == "System.Collections.Generic.ICollection<T>" ||
                originalDef == "System.Collections.Generic.IReadOnlyCollection<T>" ||
                originalDef == "System.Collections.Generic.IList<T>" ||
                originalDef == "System.Collections.Generic.IReadOnlyList<T>")
            {
                return $"{sourceParam}.Count";
            }
        }

        // Fallback to LINQ Count()
        return $"{sourceParam}.Count()";
    }

    /// <summary>
    /// Gets the element type if the given type is a supported collection type.
    /// Returns null if the type is not a collection.
    /// </summary>
    private ITypeSymbol? GetCollectionElementType(ITypeSymbol type)
    {
        // Handle arrays (T[])
        if (type is IArrayTypeSymbol arrayType)
        {
            return arrayType.ElementType;
        }

        // Handle generic collections
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType && namedType.TypeArguments.Length == 1)
        {
            var originalDef = namedType.OriginalDefinition.ToDisplayString();
            var supportedCollections = new[]
            {
                "System.Collections.Generic.List<T>",
                "System.Collections.Generic.IList<T>",
                "System.Collections.Generic.ICollection<T>",
                "System.Collections.Generic.IEnumerable<T>",
                "System.Collections.Generic.IReadOnlyList<T>",
                "System.Collections.Generic.IReadOnlyCollection<T>"
            };

            if (supportedCollections.Contains(originalDef))
            {
                return namedType.TypeArguments[0];
            }
        }

        return null;
    }

    private static IEnumerable<IPropertySymbol> GetMappableProperties(INamedTypeSymbol? type)
    {
        if (type == null)
            return Enumerable.Empty<IPropertySymbol>();

        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                       !p.IsStatic &&
                       !p.IsIndexer &&
                       p.GetMethod != null);
    }

    private static bool CanAssign(ITypeSymbol source, ITypeSymbol dest)
    {
        // Simple type compatibility check
        if (SymbolEqualityComparer.Default.Equals(source, dest))
            return true;

        // Handle Nullable<T> to T (value types)
        var sourceUnderlying = GetNullableUnderlyingType(source);
        var destUnderlying = GetNullableUnderlyingType(dest);

        if (sourceUnderlying != null && destUnderlying == null)
        {
            // Nullable<T> -> T - allowed but may throw at runtime
            return SymbolEqualityComparer.Default.Equals(sourceUnderlying, dest);
        }

        if (sourceUnderlying == null && destUnderlying != null)
        {
            // T -> Nullable<T> - always allowed
            return SymbolEqualityComparer.Default.Equals(source, destUnderlying);
        }

        // Handle nullable reference types: nullable ref -> non-nullable ref
        if (source.NullableAnnotation == NullableAnnotation.Annotated &&
            dest.NullableAnnotation != NullableAnnotation.Annotated)
        {
            var underlyingSource = source.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            return SymbolEqualityComparer.Default.Equals(underlyingSource, dest);
        }

        // Handle nullable reference types: non-nullable ref -> nullable ref (always valid)
        if (source.NullableAnnotation != NullableAnnotation.Annotated &&
            dest.NullableAnnotation == NullableAnnotation.Annotated)
        {
            var underlyingDest = dest.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
            return SymbolEqualityComparer.Default.Equals(source, underlyingDest);
        }

        // Handle inheritance
        var currentType = source;
        while (currentType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(currentType, dest))
                return true;
            currentType = currentType.BaseType;
        }

        // Handle interfaces
        foreach (var iface in source.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, dest))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Gets the underlying type for Nullable&lt;T&gt;, or null if the type is not a nullable value type.
    /// </summary>
    private static ITypeSymbol? GetNullableUnderlyingType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType &&
            namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T &&
            namedType.TypeArguments.Length == 1)
        {
            return namedType.TypeArguments[0];
        }
        return null;
    }

    /// <summary>
    /// Checks if source is Nullable&lt;T&gt; and dest is T.
    /// </summary>
    private static bool IsNullableToNonNullableValueType(ITypeSymbol source, ITypeSymbol dest)
    {
        var sourceUnderlying = GetNullableUnderlyingType(source);
        if (sourceUnderlying == null)
            return false;

        var destUnderlying = GetNullableUnderlyingType(dest);
        if (destUnderlying != null)
            return false;

        return SymbolEqualityComparer.Default.Equals(sourceUnderlying, dest);
    }

    private static string GetAccessibilityKeyword(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.Private => "private",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
    }
}
